services:
  web: 
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    # from root directory docker compose up --detach
    stop_signal: SIGINT
    ports:
      - '9876:9876'